const {
  findUserByEmail,
  getUserById,
  createUser,
  validateUserCredentials,
  getBooks,
  getBookById,
  createBook,
  updateBook,
  deleteBook,
  getAuthors,
  getAuthorById,
  getAuthorByName,
  createAuthor,
  updateAuthor,
  deleteAuthor,
} = require('./db');

module.exports = {
  findUserByEmail,
  getUserById,
  createUser,
  validateUserCredentials,
  getBooks,
  getBookById,
  createBook,
  updateBook,
  deleteBook,
  getAuthors,
  getAuthorById,
  getAuthorByName,
  createAuthor,
  updateAuthor,
  deleteAuthor,
};